$(document).ready(function(){
$("#bilibili").click(function(){
	window.open('http://space.bilibili.com/70650/');
});
$("#weibo").click(function(){
	window.open('http://weibo.com/nangongjiujiu');
});
$("#codepen").click(function(){
	window.open('http://codepen.io/992939504/');
});
$("#github").click(function(){
	window.open('https://github.com/992939504/992939504.github.io');
});
});